 // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzX_n4VPESA7pJx27O5RexVaKtqWrZmGM',
    appId: '1:918879118100:web:3a93cd0b84e3f1c4b89801',
    messagingSenderId: '918879118100',
    projectId: 'bellewise-24a9f',
    authDomain: 'bellewise-24a9f.firebaseapp.com',
    storageBucket: 'bellewise-24a9f.firebasestorage.app',
    measurementId: 'G-WVZMEH624X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJMYZ4XDSQz7tLW0O6sQ3jmq3uFZqlwaU',
    appId: '1:918879118100:android:a33c2dd9976c4670b89801',
    messagingSenderId: '918879118100',
    projectId: 'bellewise-24a9f',
    storageBucket: 'bellewise-24a9f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd1Rx9kOQp2IB7wNHGEfalcI-0_5XvTzQ',
    appId: '1:918879118100:ios:44e4ae3b3f36b1a9b89801',
    messagingSenderId: '918879118100',
    projectId: 'bellewise-24a9f',
    storageBucket: 'bellewise-24a9f.firebasestorage.app',
    iosBundleId: 'com.example.bellewiseMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd1Rx9kOQp2IB7wNHGEfalcI-0_5XvTzQ',
    appId: '1:918879118100:ios:44e4ae3b3f36b1a9b89801',
    messagingSenderId: '918879118100',
    projectId: 'bellewise-24a9f',
    storageBucket: 'bellewise-24a9f.firebasestorage.app',
    iosBundleId: 'com.example.bellewiseMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzX_n4VPESA7pJx27O5RexVaKtqWrZmGM',
    appId: '1:918879118100:web:a3f1d4065fc40181b89801',
    messagingSenderId: '918879118100',
    projectId: 'bellewise-24a9f',
    authDomain: 'bellewise-24a9f.firebaseapp.com',
    storageBucket: 'bellewise-24a9f.firebasestorage.app',
    measurementId: 'G-6Y5DFFRXPC',
  );
}
